### ISSUE TITLE
1:1 name to address mapping could lead to address squatting

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/weave#714] opened 2019-06-03 14:01 UTC
With 1:1 name to address mapping, someone could register their name to my address making it impossible for me to associate my name with my address.

Many to one name to address mappings should be allowed.

## Acceptance criteria
- [x] We can remove the index entirely with chain,address -> name
      (We only have the forward lookup name -> [chain, address])
- [x] Fix all tests and scenarios to adapt to this.
- [ ] Update docs

Discussion on the topic: https://internetofvalues.slack.com/archives/CB0U9AERL/p1559566705038100

**Comment by webmaster128** [comment] 2019-06-05 08:57
As discussed in person yesterday, this the iterative approach I am suggesting:

1. The main BNS has no reverse lokup
2. There is no chainid-address uniqueness constraint (i.e. multiple names can resolve to an address)
3. In the future we may build a reverse lookup service that allows the user to assign a name to a native address if and only if they prove to the blockchain that they are the owner of this address. This is entirely optional and may only be supported for a subset of all chains.

**Comment by ethanfrey** [comment] 2019-06-10 13:47
This is a duplicate of #736 I believe. Please merge them into one issue

**Comment by ethanfrey** [comment] 2019-06-11 12:12
- [ ] We can remove the index entirely with chain,address -> name
      (We only have the forward lookup name -> [chain, address])
- [ ] Fix all tests and scenarios to adapt to this.
- [ ] Update docs

**Closed** 2019-06-13 07:26 UTC
