### ISSUE TITLE
Increase number of allowed TX in batch

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#926] opened 2019-07-30 11:08 UTC
**Is your feature request related to a problem? Please describe.**
From the reward account we want to send cash TX to the recipients via batch operation managed by gov. Unfortunately the limit is set fix to [10](https://github.com/iov-one/weave/blob/master/x/batch/decorator.go#L16).

**Describe the solution you'd like**
We need to support 15 (@kmw101). 

**Describe alternatives you've considered**

**Additional context**
From slack: A distribution contract is not "flexible" enough for the distribution.

**Acceptance criteria**
- [ ] 15 cash.Send TX work in a single batch

**Comment by husio** [comment] 2019-08-07 07:53
Should we increment it to a much higher number? Today it's 15 participants, tomorrow it will be 16 and the issue is back. I think this should be addressed by defining the maximum upper limit. What is the scenario this limit is protecting from?

**Comment by ruseinov** [comment] 2019-08-07 08:14
We have to understand what are the performance implications for that. In theory we can go up to 50 without even checking this.

**Comment by ruseinov** [comment] 2019-08-07 08:14
@kmw101 ?

**Comment by kmw101** [comment] 2019-08-07 09:03
My understanding is there are 15 or so Validators and a bunch of Depositors. We know how many addresses to distribute to so batchtx could be called multiple times? Lets say there are 48 addresses in total, then batch is called 5 times with a limit of 10 each time (with the last one having 8)?

**Closed** 2019-08-07 15:18 UTC
Labels: :chipmunk:
