### ISSUE TITLE
Hidden panic

### ISSUE THREAD

**Issue by husio** [iov-one/weave#363] opened 2019-02-27 14:15 UTC
The current implementation of weave application is hiding panics from the user. A combination of [`Recover`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L370) and [`Redact`](https://github.com/iov-one/weave/blob/master/errors/errors.go#L361`) hides the cause behind `"internal"` string.

If an application is failing, currently this is the output. The error is `cannot check tx: internal [iov-one/weave/abci.go:114]`

```
$ go test github.com/iov-one/weave/cmd/bcpd/... -failfast
?       github.com/iov-one/weave/cmd/bcpd       [no test files]                       
--- FAIL: TestSendTx (0.00s)                              
    require.go:157:        
                Error Trace:    app_test.go:441            
                                                        app_test.go:376
                                                        app_test.go:46
                Error:          Not equal:                                                           
                                expected: 0x0                  
                                actual  : 0x1                  
                Test:           TestSendTx                                                                                               
                Messages:       cannot check tx: internal [iov-one/weave/abci.go:114]
FAIL                                           
FAIL    github.com/iov-one/weave/cmd/bcpd/app   0.007s                 
ok      github.com/iov-one/weave/cmd/bcpd/commands      2.016s        
go test github.com/iov-one/weave/cmd/bcpd/... -failfast  8,14s user 0,88s system 171% cpu 5,267 total
```
If the `Redact` call is removed a helpful error is returned

```
 $ go test github.com/iov-one/weave/cmd/bcpd/... -failfast
?       github.com/iov-one/weave/cmd/bcpd       [no test files]
--- FAIL: TestSendTx (0.00s)
    require.go:157: 
                Error Trace:    app_test.go:441
                                                        app_test.go:376
                                                        app_test.go:46
                Error:          Not equal: 
                                expected: 0x0
                                actual  : 0x1b276
                Test:           TestSendTx
                Messages:       cannot check tx: panic: cannot load "cash:collector_address" configuration: encoding/hex: invalid byte: U+006B 'k': panic [iov-one/weave/gconf/gconf.go:77]
FAIL
FAIL    github.com/iov-one/weave/cmd/bcpd/app   0.010s
```
I believe the motivation for the `Reduct` function is to not leak out the implementation to the end user. This is a correct behaviour. In current form it makes it hard on the developer as well. The real reason of a failure is hidden.

Figure out how this issue (hiding error cause) can be solved without leaking out the information to the end user.

**Acceptance Criteria**

- [x] Check for the debug mode flag on returning abci errors and don't redact if present (see https://github.com/iov-one/weave/blob/master/abci.go#L108-L109 and https://github.com/iov-one/weave/blob/master/abci.go#L126-L127)
- [x] Add a test for above behavior (to ensure it is not accidentally changed later)
- [x] Ensure this debug mode flag is set on all "full-stack" tests we run that receive abci errors
- [x] Document using this flag in binary (https://github.com/iov-one/weave/blob/master/commands/server/start.go#L25)

**Comment by ethanfrey** [comment] 2019-02-27 16:03
Yes. I was opposed to `Redact` and managed to apply it only to panics, not all internal errors, over some opposition.

I came across a similar issue in another PR and did a `fmt.Printf"%+v\n", err)` in redact, so it was exposed to the server, not the client.

I can think of three approaches:
* Setting up a proper logger for tests (to stdout, not /dev/null), such error messages will be logged in full and only redacted at the abci interface. Assuming we are in these full-stack scenario tests
* Use the debug flag to disable redacting the info as well and set debug=true in the tests
* Don't redact at all

**Comment by alpe** [comment] 2019-03-01 16:10
It is true that this is a bit painful to debug. Good to bring this up!
Adding  proper loggers would not be a big issue but the proper error message would even be nicer and can save some time looking for the root cause.

I was thinking if a `debug_client=true` flag would make sense to be able to debug the server while the internals are still hidden to the clients. But on the other hand we could just run a private node and don't expose it.

**Comment by ethanfrey** [comment] 2019-03-04 15:44
The errors are logged in full in a normal setup, meaning on a running chain, panics will be in the k8 logs at least, if not shown to clients. The main problem is that in tests, we don't use the logger, and we now don't get a message in the test client.

Running in debug mode to expose the info should be a good solution then? And use that for tests along with anyone who wants to run a private node?

**Comment by ethanfrey** [comment] 2019-05-27 14:35
4 checks means done, right?

Want to close it @husio ?

**Closed by ethanfrey** 2019-05-27 14:35 UTC
