### ISSUE TITLE
Execute gov/tally via block callback

### ISSUE THREAD

**Issue by alpe** [iov-one/weave#671] opened 2019-05-27 12:59 UTC
**Is your feature request related to a problem? Please describe.**
When the voting period of a proposal has ended a tally message needs to sent to close the proposal and execute the payload. Instead of doing this manually we should have this done by the app itself based on current block height/ time.

**Describe the solution you'd like**
We could have some callback support  that get's executed after each block like in [cosmos-sdk](
https://github.com/cosmos/cosmos-sdk/blob/master/x/gov/endblocker.go#L11)

**Additional context**
Executing callbacks on each block may add some unnecessary overhead to the block execution time.

When finished, update https://docs.google.com/a/iov.one/document/d/1se--yfQPm4KuSUzSmGun2CBPSyiVfMHDmD-CwBuBmrA/edit?disco=AAAADIOba3c

**Comment by ethanfrey** [comment] 2019-06-24 17:01
Please read some ideas (eg. cron callback) from #78 and close that issue as well when resolving this issue.

**Comment by ethanfrey** [comment] 2019-07-01 15:40
Note there is an open issue: https://github.com/tendermint/tendermint/issues/3665

Tags on BeginBlock are subscribable, not searchable. Not by design but by oversight.

Until this is fixed, I am unsure how good it is to have essential data there, which cannot be searched after the fact.

**Comment by ethanfrey** [comment] 2019-07-01 15:44
Thoughts on tagging:

* Return a unique cron job id on creations
* Creating tx stored this in abci state or data field of tx... visible to clients
* Cron job, on execution, tags begin block with `cron=<cronjob_id>`, it also writes to the abci state the cron job result.
  * Subscribers that care about a cron job can get immediate notifications from the tag
  * Offline clients can query abci state to see if it has been executed yet
* CronResult can store also error and data fields, so there is a record if it succeeded or not

**Comment by ethanfrey** [comment] 2019-07-01 15:46
DIscussion points:

* Serialze/deserialize msg (use tx/oneof)
* Serialize authentication info (in context)
* Dealing with other random context data that we need to pass? https://github.com/iov-one/weave/blob/3356f45a0bde6b49f43aea47971661b0d49324e4/x/gov/handler.go#L222-L223  (maybe we cannot run those items in cronjobs... it is just one place... maybe we remove this)
* How a client can follow execution status (pending, success, failures) - search and subscribe - of a cron job

**Comment by ethanfrey** [comment] 2019-07-11 14:26
@husio This was closed by #850 correct?

Want to close it?

**Comment by husio** [comment] 2019-07-11 14:28
:mailbox_closed:

**Closed** 2019-07-11 14:28 UTC
Labels: Launch
