### ISSUE TITLE
x/utils package improvements

### ISSUE THREAD

**Issue by ruseinov** [iov-one/weave#519] opened 2019-04-11 13:28 UTC
- [ ] Might be a good idea to extend key_tagger to allow ignoring certain keys setting them in context in other decorators/contollers

**Comment by husio** [comment] 2019-04-16 08:06
Is this story related to https://github.com/iov-one/weave/issues/445 ?

**Comment by ethanfrey** [comment] 2019-04-17 18:16
Duplicate of #445

**Closed by ethanfrey** 2019-04-17 18:16 UTC
Labels: :rabbit2: :egg:
