### ISSUE TITLE
Standardize query paths to plural

### ISSUE THREAD

**Issue by webmaster128** [iov-one/weave#810] opened 2019-06-25 10:29 UTC
In

```go
	NewElectionRulesBucket().Register("electionRules", qr)
	NewElectorateBucket().Register("electorates", qr)
	NewProposalBucket().Register("proposal", qr)
	NewVoteBucket().Register("vote", qr)
```

both bucket names and queries use mixed singular/plural. As far as I know, you use singular item names in collections in English (e.g. "message list" is correct and "messages list" is not). Thus I think the first line should be an "election rule bucket".

For the queries I think we should use plural consistently as they return a (filtered) list of items.

- [ ] `NewElectionRulesBucket` -> `NewElectionRuleBucket`
- [ ] `/proposal` -> `/proposals`
- [ ] `/vote` -> `/votes`

-----

This brings consistency with other modules, e.g.

```go
NewContractBucket().Register("contracts", qr)
NewRevenueBucket().Register("revenues", qr)
NewBucket().Register("escrows", qr)
NewBucket().Register("aswaps", qr)
```

**Comment by husio** [comment] 2019-07-09 13:38
Duplicate of https://github.com/iov-one/weave/issues/849

**Closed by husio** 2019-07-09 13:38 UTC
