### ISSUE TITLE
gov/TestCreateProposalTextHandler does not include scheduler

### ISSUE THREAD

**Issue by orkunkl** [iov-one/weave#1009] opened 2019-10-04 10:35 UTC
## Expected Behavior
here is the related code: https://github.com/iov-one/weave/blob/master/x/gov/handler_test.go#L347-L398
```go
	for testName, spec := range specs {
		t.Run(testName, func(t *testing.T) {
			auth := &weavetest.Auth{
				Signers: spec.Signers,
			}
			rt := app.NewRouter()
			cron := &weavetest.Cron{}
			// We don't run the executor here, so we can safely pass in nil.
			RegisterRoutes(rt, auth, decodeProposalOptions, nil, cron)

			db := store.MemStore()
			migration.MustInitPkg(db, packageName)

			// given
			ctx := weave.WithBlockTime(context.Background(), now.Time())
			if spec.Init != nil {
				spec.Init(t, db)
			}
			// setup election rules
			withElectionRule(t, db)
			// setup electorate
			withElectorate(t, db)

			cache := db.CacheWrap()

			// when check is called
			tx := &weavetest.Tx{Msg: &spec.Msg}
			if _, err := rt.Check(ctx, cache, tx); !spec.WantCheckErr.Is(err) {
				t.Fatalf("check expected: %+v  but got %+v", spec.WantCheckErr, err)
			}

			cache.Discard()

			// and when deliver is called
			res, err := rt.Deliver(ctx, db, tx)
			if !spec.WantDeliverErr.Is(err) {
				t.Fatalf("deliver expected: %+v  but got %+v", spec.WantCheckErr, err)
			}
			if spec.WantDeliverErr != nil {
				return // skip further checks on expected error
			}
			// and check persisted status
			p, err := NewProposalBucket().GetProposal(cache, res.Data)
			if err != nil {
				t.Fatalf("unexpected error: %s", err)
			}

			assertProposalsEqual(t, spec.Exp, *p)
			cache.Discard()
		})
	}
}
```

I expect this handler to check if the tally message is scheduled correctly.

**Comment by alpe** [comment] 2019-10-07 08:54
This is a fair request, although I would not raise it as a **bug**. If you notice missing test coverage please do a feature request or just a PR with a fix if you have capacity.

In this case I would suggest to add a new test to cover the scheduler in deliver only. That would be easier to read and maintain. Cases are:
* invalid msg -> scheduler not called, error returned
* valid msg -> scheduler called, arguments match expectations, no error returned
* valid msg, scheduler returns error -> method returns error (This causes a rollback and guarantees atomic behaviour)

**Comment by husio** [comment] 2019-10-24 08:11
I am closing this as there is no one that can take care of it anytime soon.

As Alex mentioned, missing test is not a bug.

**Closed by husio** 2019-10-24 08:11 UTC
